version: "3.8"
services:
    mysql:
        container_name: mysql
        image: mysql
        command: --default-authentication-plugin-mysql_native_password
        volumes:
            - .sql-data-db:/var/lib/mysql
        ports:
            - "3006:3306"
        enviroment:
            - MYSQL_DATABASE=ecommerce
            - MYSQL_HOST=localhost
            - MYSQL_ROOT_PASSWORD=password
    nodejs:
        build:
            context: .
        image: api_palavecino
        depends on:
            - mysql
        enviroment:
            - MYSQL_DATABASE=ecommerce
            - MYSQL_HOST=localhost
            - MYSQL_ROOT_PASSWORD=password
        ports:
            -"3333:3000"
        container_name: api